<?php
// FireZone Store Installer
$lock_file = __DIR__ . '/../config/installed.lock';
$config_file = __DIR__ . '/../config/config.php';
$is_locked = file_exists($lock_file);

$errors = [];
$success = false;

// System requirements check
$reqs = [
    'PHP Version (>= 8.0)' => version_compare(PHP_VERSION, '8.0.0', '>='),
    'PDO Extension' => extension_loaded('pdo'),
    'PDO MySQL Driver' => extension_loaded('pdo_mysql'),
    'Mbstring Extension' => extension_loaded('mbstring'),
    'Session Support' => extension_loaded('session'),
    'Config Directory Writable' => is_writable(__DIR__ . '/../config') || (!file_exists(__DIR__ . '/../config') && is_writable(__DIR__ . '/..')),
    'Uploads Directory Writable' => is_writable(__DIR__ . '/../uploads') || (!file_exists(__DIR__ . '/../uploads') && is_writable(__DIR__ . '/..')),
];
$all_reqs_met = !in_array(false, $reqs, true);

if ($_SERVER['REQUEST_METHOD'] === 'POST' && !$is_locked && $all_reqs_met) {
    $db_host = trim($_POST['db_host'] ?? '127.0.0.1');
    $db_port = trim($_POST['db_port'] ?? '3306');
    $db_name = trim($_POST['db_name'] ?? 'freefire_store');
    $db_user = trim($_POST['db_user'] ?? 'root');
    $db_pass = (string)($_POST['db_pass'] ?? '');

    $site_name = trim($_POST['site_name'] ?? 'FireZone Store');
    $currency = trim($_POST['currency_symbol'] ?? '$');

    $admin_name = trim($_POST['admin_name'] ?? 'Administrator');
    $admin_user = trim($_POST['admin_user'] ?? 'admin');
    $admin_email = trim($_POST['admin_email'] ?? 'admin@firezone.com');
    $admin_pass = (string)($_POST['admin_pass'] ?? '');

    if (empty($db_host) || empty($db_name) || empty($db_user)) {
        $errors[] = "Database Host, Database Name, and Username are required.";
    }
    if (empty($site_name)) {
        $errors[] = "Website Name is required.";
    }
    if (empty($admin_user) || empty($admin_email) || strlen($admin_pass) < 6) {
        $errors[] = "Admin Username, Email, and Password (min 6 characters) are required.";
    }

    if (empty($errors)) {
        try {
            // Step 1: Connect to MySQL server
            $dsn_no_db = "mysql:host={$db_host};port={$db_port};charset=utf8mb4";
            $pdo_server = new PDO($dsn_no_db, $db_user, $db_pass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
            ]);

            // Step 2: Create DB if not exists
            $pdo_server->exec("CREATE DATABASE IF NOT EXISTS `{$db_name}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

            // Step 3: Connect to the database
            $dsn = "mysql:host={$db_host};port={$db_port};dbname={$db_name};charset=utf8mb4";
            $pdo = new PDO($dsn, $db_user, $db_pass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
            ]);

            // Step 4: Execute SQL schema
            $sql_file = __DIR__ . '/../database/database.sql';
            if (!file_exists($sql_file)) {
                throw new Exception("Database schema file (/database/database.sql) not found.");
            }
            $sql_content = file_get_contents($sql_file);
            $pdo->exec($sql_content);

            // Step 5: Update custom settings
            $stmt = $pdo->prepare("UPDATE settings SET setting_value = ? WHERE setting_key = 'site_name'");
            $stmt->execute([$site_name]);

            $stmt = $pdo->prepare("UPDATE settings SET setting_value = ? WHERE setting_key = 'currency_symbol'");
            $stmt->execute([$currency]);

            // Step 6: Create Super Admin Account
            $hashed_password = password_hash($admin_pass, PASSWORD_DEFAULT);
            $stmt = $pdo->prepare("INSERT INTO admins (name, username, email, password, role) VALUES (?, ?, ?, ?, 'superadmin')");
            $stmt->execute([$admin_name, $admin_user, $admin_email, $hashed_password]);

            // Step 7: Write config/config.php
            $config_content = "<?php\n"
                . "// Configuration Generated by FireZone Installer\n"
                . "define('DB_HOST', " . var_export($db_host, true) . ");\n"
                . "define('DB_PORT', " . var_export($db_port, true) . ");\n"
                . "define('DB_NAME', " . var_export($db_name, true) . ");\n"
                . "define('DB_USER', " . var_export($db_user, true) . ");\n"
                . "define('DB_PASS', " . var_export($db_pass, true) . ");\n\n"
                . "define('APP_NAME', " . var_export($site_name, true) . ");\n"
                . "define('SESSION_SECURE', false);\n"
                . "date_default_timezone_set('UTC');\n";

            file_put_contents($config_file, $config_content);

            // Step 8: Create lock file to protect installer
            file_put_contents($lock_file, "Installed on " . date('Y-m-d H:i:s') . "\n");
            $is_locked = true;
            $success = true;

        } catch (Exception $e) {
            $errors[] = "Installation failed: " . $e->getMessage();
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en" class="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FireZone Installer | Free Fire Gaming Store</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            darkMode: 'class',
            theme: {
                extend: {
                    colors: {
                        gaming: {
                            950: '#07070a',
                            900: '#0a0a0f',
                            850: '#12121a',
                            800: '#181824',
                            border: '#27273a',
                            red: '#ef4444',
                        }
                    }
                }
            }
        }
    </script>
    <link rel="stylesheet" href="/assets/css/style.css">
</head>
<body class="bg-gaming-950 text-zinc-100 min-h-screen py-10 px-4 flex items-center justify-center">

<div class="max-w-2xl w-full bg-gaming-900 border border-gaming-border rounded-2xl shadow-2xl p-6 md:p-10 relative overflow-hidden">
    <!-- Red glowing ambient header -->
    <div class="absolute top-0 left-0 right-0 h-1.5 bg-gradient-to-r from-red-600 via-red-500 to-amber-500"></div>

    <div class="text-center mb-8">
        <div class="w-14 h-14 mx-auto rounded-2xl bg-gradient-to-tr from-red-600 to-amber-500 p-0.5 shadow-lg mb-4 flex items-center justify-center">
            <div class="w-full h-full bg-gaming-950 rounded-[14px] flex items-center justify-center">
                <svg class="w-8 h-8 text-red-500" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M12 2L1 21h22L12 2zm0 3.84L19.46 19H4.54L12 5.84zM11 10h2v4h-2zm0 6h2v2h-2z"/>
                </svg>
            </div>
        </div>
        <h1 class="font-gaming text-2xl md:text-3xl font-bold tracking-wider text-white">FIREZONE STORE INSTALLER</h1>
        <p class="text-xs md:text-sm text-zinc-400 mt-1">Automated Setup for PHP + MySQL Gaming Top-Up Platform</p>
    </div>

    <?php if ($success): ?>
        <div class="p-6 rounded-xl bg-emerald-950/50 border border-emerald-500/50 text-emerald-200 text-center space-y-4">
            <div class="w-12 h-12 rounded-full bg-emerald-500/20 text-emerald-400 flex items-center justify-center mx-auto text-2xl font-bold">✓</div>
            <h2 class="font-gaming text-xl font-bold text-white">INSTALLATION COMPLETE!</h2>
            <p class="text-sm text-zinc-300">
                Database schema has been initialized, initial categories created, and super admin account provisioned successfully.
            </p>
            <div class="pt-4 flex flex-col sm:flex-row gap-3 justify-center">
                <a href="/admin/login.php" class="btn-gaming-red text-white px-6 py-2.5 rounded-lg text-sm font-semibold shadow-red-glow">
                    Go to Admin Panel &rarr;
                </a>
                <a href="/index.php" class="px-6 py-2.5 rounded-lg text-sm font-semibold bg-gaming-800 hover:bg-gaming-750 text-zinc-200 border border-gaming-border">
                    Visit Store Front
                </a>
            </div>
        </div>

    <?php elseif ($is_locked): ?>
        <div class="p-6 rounded-xl bg-gaming-850 border border-amber-500/40 text-center space-y-4">
            <div class="w-12 h-12 rounded-full bg-amber-500/20 text-amber-400 flex items-center justify-center mx-auto text-xl font-bold">🔒</div>
            <h2 class="font-gaming text-xl font-bold text-amber-300">Installer Protected</h2>
            <p class="text-sm text-zinc-300">
                FireZone Store is already installed and protected. To re-run the installer, delete <code class="text-red-400 bg-gaming-950 px-1 py-0.5 rounded">config/installed.lock</code>.
            </p>
            <div class="pt-4 flex flex-col sm:flex-row gap-3 justify-center">
                <a href="/admin/login.php" class="btn-gaming-red text-white px-6 py-2.5 rounded-lg text-sm font-semibold">
                    Admin Login
                </a>
                <a href="/index.php" class="px-6 py-2.5 rounded-lg text-sm font-semibold bg-gaming-800 text-zinc-200 border border-gaming-border">
                    Store Homepage
                </a>
            </div>
        </div>

    <?php else: ?>

        <?php if (!empty($errors)): ?>
            <div class="p-4 mb-6 rounded-xl bg-red-950/60 border border-red-500/60 text-red-200 text-xs space-y-1">
                <?php foreach ($errors as $err): ?>
                    <p>• <?php echo htmlspecialchars($err, ENT_QUOTES, 'UTF-8'); ?></p>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>

        <!-- System Requirements Checklist -->
        <div class="mb-8 p-4 rounded-xl bg-gaming-850 border border-gaming-border">
            <h3 class="font-gaming text-sm font-bold text-red-400 uppercase tracking-wider mb-3">System Pre-requisites</h3>
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
                <?php foreach ($reqs as $label => $pass): ?>
                    <div class="flex items-center justify-between p-2 rounded bg-gaming-900 border border-gaming-border">
                        <span class="text-zinc-300"><?php echo htmlspecialchars($label); ?></span>
                        <span class="font-bold <?php echo $pass ? 'text-emerald-400' : 'text-red-500'; ?>">
                            <?php echo $pass ? '✓ Ready' : '✗ Missing'; ?>
                        </span>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>

        <form method="POST" action="/install/index.php" class="space-y-6">
            <!-- Database Configuration -->
            <div class="space-y-4">
                <h3 class="font-gaming text-sm font-bold text-red-400 uppercase tracking-wider flex items-center gap-2">
                    <span class="w-2 h-2 rounded-full bg-red-500"></span> 1. MySQL Database Setup
                </h3>
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div>
                        <label class="block text-xs font-medium text-zinc-300 mb-1">MySQL Host</label>
                        <input type="text" name="db_host" value="<?php echo htmlspecialchars($_POST['db_host'] ?? '127.0.0.1'); ?>" required
                               class="w-full px-3 py-2 rounded-lg bg-gaming-950 border border-gaming-border focus:border-red-500 text-sm text-white focus:outline-none">
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-zinc-300 mb-1">Port</label>
                        <input type="text" name="db_port" value="<?php echo htmlspecialchars($_POST['db_port'] ?? '3306'); ?>" required
                               class="w-full px-3 py-2 rounded-lg bg-gaming-950 border border-gaming-border focus:border-red-500 text-sm text-white focus:outline-none">
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-zinc-300 mb-1">Database Name</label>
                        <input type="text" name="db_name" value="<?php echo htmlspecialchars($_POST['db_name'] ?? 'freefire_store'); ?>" required
                               class="w-full px-3 py-2 rounded-lg bg-gaming-950 border border-gaming-border focus:border-red-500 text-sm text-white focus:outline-none">
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-zinc-300 mb-1">Database Username</label>
                        <input type="text" name="db_user" value="<?php echo htmlspecialchars($_POST['db_user'] ?? 'root'); ?>" required
                               class="w-full px-3 py-2 rounded-lg bg-gaming-950 border border-gaming-border focus:border-red-500 text-sm text-white focus:outline-none">
                    </div>
                    <div class="sm:col-span-2">
                        <label class="block text-xs font-medium text-zinc-300 mb-1">Database Password</label>
                        <input type="password" name="db_pass" placeholder="(Leave blank if no password)"
                               class="w-full px-3 py-2 rounded-lg bg-gaming-950 border border-gaming-border focus:border-red-500 text-sm text-white focus:outline-none">
                    </div>
                </div>
            </div>

            <!-- Website Settings -->
            <div class="space-y-4 pt-4 border-t border-gaming-border">
                <h3 class="font-gaming text-sm font-bold text-red-400 uppercase tracking-wider flex items-center gap-2">
                    <span class="w-2 h-2 rounded-full bg-red-500"></span> 2. Store Configuration
                </h3>
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div>
                        <label class="block text-xs font-medium text-zinc-300 mb-1">Store Name</label>
                        <input type="text" name="site_name" value="<?php echo htmlspecialchars($_POST['site_name'] ?? 'FireZone Store'); ?>" required
                               class="w-full px-3 py-2 rounded-lg bg-gaming-950 border border-gaming-border focus:border-red-500 text-sm text-white focus:outline-none">
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-zinc-300 mb-1">Currency Symbol</label>
                        <input type="text" name="currency_symbol" value="<?php echo htmlspecialchars($_POST['currency_symbol'] ?? '$'); ?>" required
                               class="w-full px-3 py-2 rounded-lg bg-gaming-950 border border-gaming-border focus:border-red-500 text-sm text-white focus:outline-none">
                    </div>
                </div>
            </div>

            <!-- Super Admin Details -->
            <div class="space-y-4 pt-4 border-t border-gaming-border">
                <h3 class="font-gaming text-sm font-bold text-red-400 uppercase tracking-wider flex items-center gap-2">
                    <span class="w-2 h-2 rounded-full bg-red-500"></span> 3. Super Admin Account
                </h3>
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div>
                        <label class="block text-xs font-medium text-zinc-300 mb-1">Admin Full Name</label>
                        <input type="text" name="admin_name" value="<?php echo htmlspecialchars($_POST['admin_name'] ?? 'Store Owner'); ?>" required
                               class="w-full px-3 py-2 rounded-lg bg-gaming-950 border border-gaming-border focus:border-red-500 text-sm text-white focus:outline-none">
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-zinc-300 mb-1">Admin Username</label>
                        <input type="text" name="admin_user" value="<?php echo htmlspecialchars($_POST['admin_user'] ?? 'admin'); ?>" required
                               class="w-full px-3 py-2 rounded-lg bg-gaming-950 border border-gaming-border focus:border-red-500 text-sm text-white focus:outline-none">
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-zinc-300 mb-1">Admin Email</label>
                        <input type="email" name="admin_email" value="<?php echo htmlspecialchars($_POST['admin_email'] ?? 'admin@firezone.com'); ?>" required
                               class="w-full px-3 py-2 rounded-lg bg-gaming-950 border border-gaming-border focus:border-red-500 text-sm text-white focus:outline-none">
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-zinc-300 mb-1">Admin Password (min 6 chars)</label>
                        <input type="password" name="admin_pass" value="admin123" required
                               class="w-full px-3 py-2 rounded-lg bg-gaming-950 border border-gaming-border focus:border-red-500 text-sm text-white focus:outline-none">
                    </div>
                </div>
            </div>

            <button type="submit" <?php echo !$all_reqs_met ? 'disabled' : ''; ?>
                    class="w-full btn-gaming-red py-3 rounded-xl font-gaming text-base font-bold text-white tracking-wider shadow-red-glow disabled:opacity-50">
                INSTALL FIREZONE STORE NOW &rarr;
            </button>
        </form>

    <?php endif; ?>
</div>

</body>
</html>
